In [2]:
import numpy as np
a = np.array([1,2, 3, []]) 
a[-1].append(4)
a[-1].append(5)
print(len(a))

4


In [4]:
import numpy as np 
a = np.ones(2)
b = np.ones((1,2))
print(a)
print(b)

[1. 1.]
[[1. 1.]]


In [5]:
import numpy as np
a = np.array([[1,2,3], [4,5,6]])
b = a.T
print(b)

[[1 4]
 [2 5]
 [3 6]]


In [6]:
import numpy as np

np.random.random((2,2))

array([[0.04226003, 0.66781234],
       [0.24768158, 0.07775871]])

In [7]:
import numpy as np
a = np.array( [[1,2, 3, 4],  [5,6, 7, 8],  [9,10,11,12]] )
b = a[1:3, 2:]
print(b)

[[ 7  8]
 [11 12]]


In [8]:
import numpy as np 

a = np.array([[10, 11, 12]])
b = np.array([[20], [21], [22]])
c = np.array([[1,2], [3,4], [5,6]])
print(a.shape, b.shape, c.shape)

(1, 3) (3, 1) (3, 2)


In [10]:
import numpy as np
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
a[0] = a[0,::-1]
a[:,1]=a[::-1,1]
print(a)

[[ 5  7  3  2  1]
 [ 6  4  8  9 10]]


In [14]:
import numpy as np
a = np.array([[1,2, 3], [4,5,6]]) 
b = a.reshape(-1)
print(b)

[1 2 3 4 5 6]


In [15]:
import numpy as np 

a = np.zeros((2,2))

b = np.eye(2)
print(a)
print(b)

[[0. 0.]
 [0. 0.]]
[[1. 0.]
 [0. 1.]]


In [16]:
import numpy as np 
a = np.array([[1, 0], [2, -1]])
r = a * a
print(r)

[[1 0]
 [4 1]]


In [18]:
import numpy as np
a = np.array([[1,2], [3,4]])
#A list comprehension 
b = [a[j,i] for i in range(a.shape[0]) for j in range(a.shape[1])]
print(b)

[1, 3, 2, 4]


In [19]:
import numpy as np
a = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])
a[-1,-1] = 0
a[a.shape[0]-2, 1] = a[0, -1] + a[-1, 0]
a[0,0]= a[0,2] + a[2,0]
print(a)

[[10  2  3]
 [ 4 10  6]
 [ 7  8  0]]


In [20]:
import numpy as np 
a = np.array([[1, 1], [2, 0]])
b = np.matrix(a)
I = np.identity(2)
x = a * I
y = b * I
print(x)
print(y)

[[1. 0.]
 [0. 0.]]
[[1. 1.]
 [2. 0.]]


In [21]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]])
print(a[0,1], a[1,2], a[0,2])

2 6 3


In [22]:
import numpy as np 
a = np.zeros((2,2))
b = np.eye(2)
print(a)
print(b)

[[0. 0.]
 [0. 0.]]
[[1. 0.]
 [0. 1.]]


In [23]:
import numpy as np
a = np. array([ [1, 2], [3, 4] ])
print(round(np.var(a),2) == round(np.std(a)**2,2))

True


In [25]:
import numpy as np 
a = np.matrix([[1, 0], [2, -1]])
r = a * a
print(r)

[[1 0]
 [0 1]]


In [26]:
import numpy as np 

b = np.mat([[5, 6], [7, 8]])

In [27]:
b.dtype

dtype('int32')

In [28]:
import numpy as np 
a = np.array([[1, 1], [2, 0]])
b = np.matrix(a)
I = np.identity(2)
x = a * I
y = b * I
print(x)
print(y)

[[1. 0.]
 [0. 0.]]
[[1. 1.]
 [2. 0.]]


In [29]:
import numpy as np
a = np. array([ [1, 2], [3, 4] ]) 
print(np.mean(a, axis=None)== np.mean(a))

True
