# Trevor O'Connell
## Week 11: 11/05/2020
### Python NumPy Universal Functions

In [1]:
import numpy as np

arr1 = [1,2,3,4,5,6,7,8,9]

arr2 = [11,12,13,14,15,16,17,18,19]

z=[]

for i, j in zip(arr1, arr2):
    z.append(i + j)
    
z

[12, 14, 16, 18, 20, 22, 24, 26, 28]

In [2]:
#zip

fname=("Alice","bob","Christy")
lname = ("Charlie", "Clark","Robert")

flname = zip(fname,lname)
print(tuple(flname))

(('Alice', 'Charlie'), ('bob', 'Clark'), ('Christy', 'Robert'))


In [3]:
lst1 = [1,2,3,4,5]
lst2 = [10,11,12,13,14]

print(list(zip(lst1,lst2)))

[(1, 10), (2, 11), (3, 12), (4, 13), (5, 14)]


In [4]:
import numpy as np

arr = np.arange(21)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [5]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595])

In [6]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08])

In [7]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [8]:
arr1 = np.random.randn(10)
arr1

array([ 0.57921482, -0.18566119,  0.98628114,  0.82703192, -0.72145819,
        0.03830158, -0.96584825, -0.43206082,  0.82019644,  0.20361161])

In [9]:
arr2 = np.random.randn(10)

arr2

array([ 0.57572533,  0.19245335,  1.56223975,  0.31142124, -0.68273171,
       -2.0522859 ,  0.70540516,  0.01379122,  0.02762336, -1.65019788])

In [10]:
np.add(arr1,arr2)

array([ 1.15494015,  0.00679215,  2.54852089,  1.13845316, -1.4041899 ,
       -2.01398432, -0.2604431 , -0.4182696 ,  0.8478198 , -1.44658627])

In [11]:
np.maximum(arr1,arr2)

array([ 0.57921482,  0.19245335,  1.56223975,  0.82703192, -0.68273171,
        0.03830158,  0.70540516,  0.01379122,  0.82019644,  0.20361161])

In [12]:
#np.where
arr = np.arange(9).reshape((3,3))

arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
print(arr <4)

[[ True  True  True]
 [ True False False]
 [False False False]]


In [14]:
np.where(arr < 4,-1,-2)

array([[-1, -1, -1],
       [-1, -2, -2],
       [-2, -2, -2]])

In [15]:
np.where((arr < 4) & (arr>2),-1,-2)

array([[-2, -2, -2],
       [-1, -2, -2],
       [-2, -2, -2]])

In [16]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

arr_b = np.array([True, False, True, True, False])

print(arr1)
print(arr2)
print(arr_b)

print(list(zip(arr1,arr2,arr_b)))

[1 2 3 4 5]
[10 20 30 40 50]
[ True False  True  True False]
[(1, 10, True), (2, 20, False), (3, 30, True), (4, 40, True), (5, 50, False)]


In [17]:
#using list comprehension
arr3 = [r1 if c else r2 for r1,r2,c in zip(arr1,arr2,arr_b)]

arr3

[1, 20, 3, 4, 50]

In [18]:
# using np.where
arr3 = np.where(arr_b,arr1,arr2)

arr3

array([ 1, 20,  3,  4, 50])

In [20]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
cond = np.array([[True, False],[True, True]])

np.where(cond,arr1,arr2)

array([[1, 6],
       [3, 4]])

In [21]:
np.where([[True, False],[True, True]],[[5,6],[7,8]], [[1,2],[3,4]])

array([[5, 2],
       [7, 8]])

In [23]:
from numpy.random import randn
arr = randn(3,3)
arr

array([[ 0.16803536,  0.2705441 , -0.83638527],
       [ 0.87404963,  1.00754666, -0.75695503],
       [ 0.98664512,  1.9177217 ,  1.10500836]])

In [26]:
np.where(arr<0, 0,arr)

array([[0.16803536, 0.2705441 , 0.        ],
       [0.87404963, 1.00754666, 0.        ],
       [0.98664512, 1.9177217 , 1.10500836]])

In [27]:
arr_b = np.array([True,False,True,False,False])
arr_b.any()

True

In [28]:
arr_b.all()

False

In [29]:
fruits = np.array(['Apple','Cherry','Apple','Orange','Cherry','Banana'])
np.unique(fruits)

array(['Apple', 'Banana', 'Cherry', 'Orange'], dtype='<U6')

In [31]:
np.in1d(['Apple','Cherry','Grape'],fruits)

array([ True,  True, False])

In [33]:
#Statistical Measures
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape)
print(arr)

(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [34]:
arr.sum()

45

In [35]:
arr.sum(0)

array([12, 15, 18])

In [36]:
arr.sum(1)

array([ 6, 15, 24])

In [37]:
arr.sum(2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [38]:
print(arr)
np.sum(arr, axis=0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([12, 15, 18])

In [39]:
print(arr)
np.sum(arr, axis=1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([ 6, 15, 24])

In [40]:
print(arr)
np.sum(arr, axis=None)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


45

In [41]:
arr.mean()

5.0

In [42]:
print(arr)
arr.mean(0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([4., 5., 6.])

In [43]:
print(arr)
arr.mean(1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([2., 5., 8.])

In [44]:
np.mean(arr, axis=0)


array([4., 5., 6.])

In [45]:
np.mean(arr, axis=1)

array([2., 5., 8.])

In [46]:
arr.var()

6.666666666666667

In [47]:
arr.std()

2.581988897471611

In [48]:
arr = np.array([3,6,8,1,9,10,3,5,63,9,12,10,15,11,14])
arr.sort()
arr

array([ 1,  3,  3,  5,  6,  8,  9,  9, 10, 10, 11, 12, 14, 15, 63])

In [49]:
#Identity array
i = np.eye(5)
i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [51]:
a = np.arange(25).reshape((5,5))

a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [52]:
a * i

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  6.,  0.,  0.,  0.],
       [ 0.,  0., 12.,  0.,  0.],
       [ 0.,  0.,  0., 18.,  0.],
       [ 0.,  0.,  0.,  0., 24.]])

In [54]:
i = np.eye(2)
print(i)
a = np.arange(4).reshape((2,2))
print(a)
a*i

[[1. 0.]
 [0. 1.]]
[[0 1]
 [2 3]]


array([[0., 0.],
       [0., 3.]])

In [56]:
m = np.mat([[1,2],[3,4]])

m

matrix([[1, 2],
        [3, 4]])

In [57]:
m * i

matrix([[1., 2.],
        [3., 4.]])

In [58]:
# Transpose

arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)
print(arr)
print('--------------------')

t = arr.T
t

(2, 4)
[[1 2 3 4]
 [5 6 7 8]]
--------------------


array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [60]:
arr.transpose()

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [61]:
arr.transpose((0,1))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [62]:
arr.transpose((1,0))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [64]:
arr_3d = np.arange(20).reshape((2,5,2))

print(arr_3d)
print(arr_3d.shape)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]
(2, 5, 2)


In [65]:
arr_3d.transpose((0,1,2))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [66]:
arr_3d.transpose((1,0,2))

array([[[ 0,  1],
        [10, 11]],

       [[ 2,  3],
        [12, 13]],

       [[ 4,  5],
        [14, 15]],

       [[ 6,  7],
        [16, 17]],

       [[ 8,  9],
        [18, 19]]])

In [67]:
np.random.random((4,4))

array([[0.66955079, 0.54454245, 0.20648857, 0.20247943],
       [0.69803039, 0.5366156 , 0.28634974, 0.61507112],
       [0.70550456, 0.4992124 , 0.38097952, 0.31645032],
       [0.88416715, 0.21201341, 0.6059867 , 0.03636251]])

In [68]:
from numpy.random import random
random((4,4))

array([[0.167335  , 0.44347873, 0.2933934 , 0.85786015],
       [0.77151142, 0.86873637, 0.37540172, 0.92664185],
       [0.13712895, 0.65081472, 0.41803736, 0.61330772],
       [0.02606101, 0.42222844, 0.20036464, 0.21865558]])

In [69]:
from numpy.random import randn
randn(5,5)

array([[ 0.51540241,  1.04354595, -1.48933593,  1.89161924, -0.35689348],
       [ 0.04344571,  2.0612982 ,  1.36905822,  0.68809286,  0.95368454],
       [ 0.9123696 , -2.06668256,  1.18601814, -0.48724952, -1.55646715],
       [ 0.51246567, -0.96312489,  1.32446002,  0.84782422,  0.22492894],
       [ 0.33825924,  0.83402365, -0.28952174,  1.61479454, -0.73346439]])

In [70]:
randn(5)

array([ 0.2886237 , -1.00923085,  0.59891509, -0.32325524,  0.41586875])

In [71]:
np.random.randint(10,50)

16

In [73]:
website = "http://docs.scipy.org/doc/numpy/reference/ufuncs.html#avaliable-ufuncs"

import webbrowser
webbrowser.open(website)

True

In [74]:
import pandas as pd